Repository granitify/granitify, pull requests merged in 2022-08, with the labels that each got.

#43 Adding testing framework, unit tests for archiver, integration tests for API
  .github/workflows/node.js.yml
  __tests__/api.test.js
  __tests__/archiver.test.js
  bot/archiver.js
  package-lock.json
  package.json
Labels: enhancement

#48 Additional testing configuration
  __tests__/api.test.js
  bot/bot.js
  jest-setup.js
  jest-teardown.js
  package-lock.json
  package.json
  server/models/ExampleModel.js
  server/routes/api.js
  server/server.js
Labels: enhancement

#54 Update GHA workflow to use GH secrets
  .github/workflows/node.js.yml
Labels: bug

#47 added deleteOne model to resourceContoller
  server/controllers/resourceController.js
Labels: enhancement

#56 Enable testing using GH secrets in GHA, avoid sourcing files that don't exist if using env vars
  .github/workflows/node.js.yml
  bot/bot.js
  bot/deploy-commands.js
  server/models/ResourceModel.js
Labels: bug

#63 Cutting version 1.0.0
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/node.js.yml
  .gitignore
  FrontendModelUpdated.png
  README.md
  __tests__/api.test.js
  __tests__/archiver.test.js
  bot/archiver.js
  bot/bot.js
  bot/deploy-commands.js
  client/App.js
  client/components/FilterMenu.jsx
  client/components/ResourceDisplay.jsx
  client/components/SearchMenu.jsx
  client/containers/MainContainer.jsx
  client/index.js
  client/services/resource.js
  jest-setup.js
  jest-teardown.js
  package-lock.json
  package.json
  public/index.html
  sample-objects.json
  server/controllers/exampleController.js
  server/controllers/resourceController.js
  server/controllers/resourceParserController.js
  server/models/ExampleModel.js
  server/models/ResourceModel.js
  server/routes/api.js
  server/routes/archive.js
  server/routes/example.js
  server/routes/resource.js
  server/server.js
  styles/app.scss
  webpack.config.js
Labels: release
