Repository granitify/granitify, pull requests merged in 2022-07, with the labels that each got.

#29 Update README.md with React structure from whiteboarding session with jmok3634
  README.md
Labels: documentation

#28 Added archiver.js, added call to archiver.send in bot.js
  bot/archiver.js
  bot/bot.js
Labels: enhancement

#33 Updated spec with camelCasing, updated sample objects
  README.md
  sample-objects.json
Labels: bug, documentation

#34 fixed issue with webpack trying to parse sample-objects.json
  webpack.config.js
Labels: bug

#36 Samson/discord server api
  bot/bot.js
Labels: enhancement, do not merge
